### ISSUE TITLE
Demo container fails to build, missing data?

### ISSUE THREAD

**Issue by jeaton32** [gpuopenanalytics/demo-docker#14] opened 2017-10-02 17:57 UTC
Looks like the container is not able to find the dataset, the base container builds ok, but the demo fails with a timeout, as of 9/25/2017 anyway

**Comment by jeaton32** [comment] 2017-10-02 18:17
This is the step that fails:
Step 4/33 : RUN wget -nv http://archive.ics.uci.edu/ml/machine-learning-databases/00344/Activity%20recognition%20exp.zip -O "data/Activity recognition exp.zip"
 ---> Running in 75e9c05282ad
2017-10-02 18:06:32 URL:http://archive.ics.uci.edu/ml/machine-learning-databases/00344/Activity%20recognition%20exp.zip [777127275/777127275] -> "data/Activity recognition exp.zip" [1]

**Comment by thatcort** [comment] 2018-02-13 17:25
I similarly get an error message:
```
$ docker build -t goai/demo:latest ./demo
Sending build context to Docker daemon  11.85MB
Step 1/38 : FROM goai/base:latest
pull access denied for goai/base, repository does not exist or may require 'docker login'
```
Is GOAI still an active/supported project?

**Comment by michael-balint** [comment] 2018-02-24 18:34
@thatcort - did you do the base build step?

```
cd notebook-demo-docker
docker build -t goai/base:latest ./base
docker build -t goai/demo:latest ./demo
nvidia-docker run -p 8888:8888 -ti goai/demo:latest
```

Just confirmed that this works on a newly-cloned repo on a new system.

**Comment by michael-balint** [comment] 2018-03-02 18:05
Closing this since the current version works.

**Closed by michael-balint** 2018-03-02 18:05 UTC
